spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    host: rabbitmq
    port: 5672
    addresses: ${RMQ_ADDRESS}

  config:
    activate:
      on-profile: prod




